### ISSUE TITLE
Cairo Basics - Felt ranges

### ISSUE THREAD

**Issue by kaliberpoziomka** [ctrlc03/ctrlc03.github.io#1]
Thanks for this article!

Wanted to note that the range of integers in Cairo depends on interpretation. If we interpret `felts` as the signed integers, then the range is `[-P/2, P/2)`. But if we interpret `felts` as the unsigned integers, the range is `[0, P)`.
In the _Cairo Basics_ section you mentioned just the _signed_ range, so I recommend to add also the _unsigned_. range Here is a link to documentation: https://www.cairo-lang.org/docs/how_cairo_works/builtins.html#range-checks

**Comment by ctrlc03** [comment]
Thanks for pointing this out, I've added the unsigned range too :)
